"use strict";
const PREMIUM_MICROCOPY = {
  banner: {
    subtitle: "v{{version}} | Your local AI bridge",
    onboardingSubtitle: "v{{version}} | Let's get you set up",
    compactSubtitle: "v{{version}}",
  },
  icons: {
    success: "✓",
    warning: "⚠",
    error: "✗",
    info: "ℹ",
  },
  labels: {
    nextSteps: "Next steps:",
  },
  trust: {
    control: {
      login: "Connect only trusted accounts.",
      setup: "Review settings before confirmation.",
      status: "Reading local status only.",
      statusVerbose: "Verbose mode: all data is read locally. Nothing is sent externally.",
    },
    preflight: {
      title: "Permission Check",
      confirm: "Approve this action?",
      cancelled: "Action cancelled before any changes were made.",
      labels: {
        reason: "Why:",
        action: "Action:",
        touches: "Touches:",
      },
      reasonDefault: "Apply requested operation.",
      actionDefault: "droxy",
      noFileChanges: "No file changes expected",
      cancelHint: "Cancel key: n",
      reasons: {
        setup: "Setup writes local config and state files.",
        start: "Starting proxy updates runtime state and opens a local port.",
        stop: "Stopping proxy can terminate the local Droxy process.",
        stopForce: "Force stop may terminate whichever process owns the configured port.",
        restart: "Restart stops then starts the local Droxy process.",
        login: "Login opens browser auth and updates local auth/session files.",
        droidSync: "Sync rewrites Droxy-managed model entries in Droid config files.",
        pluginInstall: "Plugin install runs Droid plugin commands and updates local plugin state.",
        pluginUninstall: "Plugin uninstall removes Droxy plugin registration from Droid.",
      },
    },
    undo: {
      setup: "Undo: run `droxy setup` again to rewrite config with new values.",
      start: "Undo: run `droxy stop`.",
      stop: "Undo: run `droxy start`.",
      restart: "Undo: run `droxy stop` if you want Droxy offline.",
      login: "Undo: run `droxy login` again to refresh or switch accounts.",
      droidSync:
        "Undo: restore `~/.factory/config.json.bak` (if available), then re-run `droxy droid sync`.",
      pluginInstall: "Undo: run `droxy plugin uninstall`.",
      pluginUninstall: "Undo: run `droxy plugin install`.",
    },
  },
  help: {
    quickStartTitle: "Quick start:",
    commandsTitle: "Commands:",
    aliasesTitle: "Task aliases:",
    navigationTitle: "Navigation:",
    quickStart: {
      menu: "Open guided menu",
      start: "Start local proxy",
      connect: "Connect provider account",
      health: "Run health check",
    },
    commands: {
      run: "Auto start and open menu",
      setup: "Run setup wizard",
      start: "Start the daemon",
      stop: "Stop the daemon",
      restart: "Restart daemon",
      status: "Show status",
      login: "Connect accounts",
      accounts: "List accounts",
      accountAdd: "Add account",
      doctor: "Health check",
      pluginInstall: "Install plugin",
      pluginUninstall: "Uninstall plugin",
      droidSync: "Sync models to Droid",
      paths: "Show paths",
      help: "Show help",
    },
    aliases: {
      connect: "Alias for droxy login",
      health: "Alias for droxy doctor",
      check: "Alias for droxy doctor",
      diagnose: "Alias for droxy doctor",
    },
    navigation: {
      move: "Move selection",
      select: "Select",
      quickJump: "Quick jump",
      toggle: "Toggle (multi-select)",
      selectAll: "Select all / none",
      showHelp: "Show help",
      backOrExit: "Go back / Exit",
    },
  },
  menu: {
    titles: {
      whereToNext: "Where to next?",
    },
    hints: {
      selected: "selected",
      spaceToggle: "space toggle",
      selectAllNone: "a all / n none",
      navigate: "↑↓ navigate",
      enterSelect: "enter select",
      escapeBack: "esc back",
      escapeQuit: "esc/q quit",
    },
    help: {
      title: "Keyboard Shortcuts",
      pressAnyKey: "Press any key to continue...",
      upDown: "Move selection",
      enter: "Select item",
      esc: "Go back or exit",
      space: "Toggle selection",
      a: "Select all",
      n: "Select none",
      question: "Show this help",
    },
    status: {
      quickJump: "Jumped to #{{index}}",
      selectedAll: "All options selected",
      selectedNone: "Selection cleared",
      selectionChanged: "{{selected}} selected",
      backToMenu: "Back to menu",
      opening: "Opening {{label}}",
    },
  },
  status: {
    title: "Status",
    state: {
      running: "running",
      blocked: "blocked",
      stopped: "stopped",
    },
    fields: {
      status: "Status:",
      host: "Host:",
      port: "Port:",
      config: "Config:",
    },
    panel: {
      title: "Status",
      proxy: "Proxy:",
      endpoint: "Endpoint:",
      config: "Config:",
      apiKey: "API Key:",
      mgmtKey: "Mgmt Key:",
      droid: "Droid:",
      models: "Models:",
      thinking: "Thinking:",
      lastSync: "Last sync:",
      lastLogin: "Last login:",
      blocked: "Blocked",
      running: "Running",
      stopped: "Stopped",
    },
  },
  header: {
    mainSubtitle: "v{{version}} | Factory Edition",
    compactTitle: "Droxy",
    compactVersion: "v{{version}}",
    fields: {
      status: "Status:",
      endpoint: "Endpoint:",
      apiKey: "API Key:",
      droid: "Droid:",
    },
    state: {
      running: "Running",
      stopped: "Stopped",
      blocked: "Blocked",
    },
    nextSteps: {
      portBlocked: "Port blocked - check your configuration",
      startDroxy: "Start Droxy to begin",
      connectAccount: "Connect an account",
      chooseModels: "Open Choose models",
      enableSync: "Open Droid sync to enable sync",
      ready: "Ready to use",
    },
  },
  onboarding: {
    cancelled: "Setup cancelled.",
    intro: "Welcome to Droxy. We'll configure secure defaults so you can connect your AI accounts and start coding.",
    keyTip: "Tip: keep these keys private. You will paste the API key into clients.",
    generatedKeys: "Generated secure keys for local access.",
    configWritten: "Config written to: {{path}}",
    startingForConnect: "Starting Droxy so account connections work.",
    droidMissing: "Droid CLI not found. Install it to sync models automatically.",
    detectModels: "We will detect models from your connected accounts.",
    steps: {
      welcome: "Welcome",
      engine: "Droxy engine",
      secureAccess: "Secure access",
      connect: "Connect accounts",
      droid: "Droid integration",
    },
    titles: {
      engineSettings: "Engine settings",
      summary: "Summary",
    },
    prompts: {
      continueSetup: "Continue with setup?",
      customizeEngine: "Customize host, port, or auth directory?",
      customizeKeys: "Customize API and management access keys?",
      writeConfig: "Write config and continue?",
      connectNow: "Connect provider accounts now?",
      autoConfigDroid: "Auto-configure Droid with your connected models?",
      keepRunning: "Keep Droxy running after setup?",
    },
  },
  login: {
    noProvidersConnected: "No providers connected yet.",
  },
  setup: {
    rerunPrompt: "Config exists. Re-run setup and overwrite?",
  },
  sync: {
    noConfig: "No config found. Run `droxy setup` to create one.",
  },
  doctor: {
    title: "Health Check",
    nextStepsTitle: "Next steps:",
    summary: {
      errors: "Issues found. Run the suggested commands to fix.",
      warnings: "Droxy is working. A few things could be better.",
      ok: "Everything looks good. You're all set.",
    },
  },
  errors: {
    connectionRefused: "Connection refused.",
    connectionRefusedHint: "Is the proxy running?",
    connectionRefusedTry: "Try: droxy start",
    configMissing: "Config not found.",
    configMissingTry: "Try: droxy setup",
    portInUse: "Port already in use.",
    portInUseTry: "Try: droxy stop --force",
    authFailed: "Authentication failed.",
    authFailedTry: "Try: droxy login",
    timeout: "Operation timed out.",
    timeoutTry: "Try again or check network.",
    unknown: "Unexpected error.",
    unknownTry: "Try: droxy doctor",
  },
  nextSteps: {
    afterStart: "Next: droxy login",
    afterStop: "Next: droxy start",
    afterSetup: "Next: droxy start",
    afterLogin: "Next: droxy status",
    afterDoctor: "Run suggested commands.",
    afterStatus: "All systems ready.",
  },
  runtime: {
    syncing: "Syncing...",
    proxy: {
      noConfig: "No config found. Run `droxy setup` to create one.",
      updateAvailable: "Proxy update available: v{{version}}.",
      updateNextRestart: " Will apply on next restart.",
      updateEnableAuto: " Set DROXY_AUTO_UPDATE=1 to install.",
      updateBackground: " Updating in background.",
      portInUseNonDroxy: "Port is in use by a non-Droxy process. Update your config or free the port.",
      alreadyRunning: "Droxy is already running on {{host}}:{{port}}",
      binaryMissing: "Engine binary not found: {{path}}",
      binaryHint: "Set DROXY_PROXY_BIN or run `droxy start` to install a local engine copy.",
      started: "Droxy started (pid {{pid}}).",
      endpoint: "Endpoint: {{endpoint}}",
      config: "Config: {{path}}",
      ensurePortInUseNonDroxy: "Port is in use by a non-Droxy process.",
      ensurePortInUseAnotherApp: "Port is in use by another app.",
      ensureWarming: "Droxy engine is still warming up.",
      stoppedWithPid: "Stopped Droxy (pid {{pid}}).",
      alreadyStopped: "Droxy is already stopped.",
      stopFailedMaybeStopped: "Failed to stop Droxy. It may already be stopped.",
      notRunning: "Droxy is not running.",
      stopBlocked: "Port is in use by a non-Droxy process.",
      stopNeedsForce: "Droxy is running but PID is unknown. Use `droxy stop --force` to stop it.",
      stopUnsupported: "Unable to stop without PID on this platform.",
      stopRefused: "Refused to stop: port is used by a non-Droxy process.",
      stopPidNotFound: "Unable to find the process using the configured port.",
      stopFailed: "Failed to stop Droxy.",
      restartSkippedStillRunning: "Droxy is still running. Restart skipped.",
      restartSkippedBlocked: "Port is in use by a non-Droxy process. Restart skipped.",
    },
    loginUi: {
      authBrowserOpen: "A browser window will open for authentication.",
      callbackPort: "Callback port:",
      waitingForAuth: "Waiting for authentication...",
      connected: "connected",
    },
    droid: {
      snippetTitle: "Factory Droid BYOK snippet (settings.json):",
      replaceApiKey: "Replace {{apiKey}} with your actual key.",
    },
    paths: {
      title: "Locations",
      appDir: "App dir:",
      config: "Config:",
      binary: "Binary:",
    },
    plugin: {
      droidNotFoundRegister: "Droid CLI not found. Cannot register plugin.",
      alreadyRegistered: "Droxy plugin already registered with Droid.",
      marketplaceMissing: "Droxy marketplace not found at {{path}}.",
      registering: "Registering Droxy as Droid plugin...",
      registered: "Droxy plugin registered with Droid",
      registerFailed: "Failed to register plugin",
      unregistered: "Droxy plugin unregistered from Droid",
    },
  },
};
const CLASSIC_MICROCOPY = {
  banner: {
    subtitle: "v{{version}} • FACTORY EDITION",
    compactSubtitle: "v{{version}}",
  },
  labels: {
    nextSteps: "Suggestions:",
  },
  onboarding: {
    cancelled: "Onboarding cancelled.",
    detectModels: "We'll detect models from your connected accounts.",
  },
  login: {
    noProvidersConnected: "No providers connected.",
  },
  doctor: {
    nextStepsTitle: "Suggestions:",
  },
  header: {
    mainSubtitle: "v{{version}} • Factory Edition",
  },
};
module.exports = {
  CLASSIC_MICROCOPY,
  PREMIUM_MICROCOPY,
};
