name: Question / Help
description: Ask for usage help or guidance
title: "[question] "
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        Ask anything. New-to-CLI questions are welcome.

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What are you trying to do?
      placeholder: Describe your goal in plain language.
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: What you already tried
      placeholder: Commands or steps you tried (if any).
      render: shell
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: Windows 11 / macOS 15 / Ubuntu 24.04
    validations:
      required: false

  - type: textarea
    id: output
    attributes:
      label: Relevant output (redacted)
      description: Paste any error or command output and remove secrets.
      render: shell
    validations:
      required: false
